{
    "Atlanta": [
        "Mike Scott", 
        "Shelvin Mack", 
        "KyleKorver", 
        "teague0", 
        "Hawks", 
        "al_horford", 
        "mikescott", 
        "Paulmillsap4", 
        "Gustavo Ayon", 
        "johnnycashvu23", 
        "Paul Millsap", 
        "Brand", 
        "teamlou23", 
        "ShelvinMack", 
        "DeMarre Carroll", 
        "The Dominican Stallion", 
        "Louis Williams", 
        "TheRealIEB42", 
        "mikejawz", 
        "ATLHawks", 
        "Mike Muscala", 
        "Mack", 
        "ATL", 
        "John Jenkins", 
        "Elton Brand", 
        "Philips Arena", 
        "The Highlight Factory", 
        "antic12pero", 
        "Cartie Martin", 
        "Jeff Teague", 
        "Schroder", 
        "Horf", 
        "DeMarreCarroll1", 
        "Pero Antic", 
        "Atlanta Hawks", 
        "Dennis Schroder", 
        "Kyle Korver", 
        "Al Horford"
    ], 
    "Boston": [
        "Smokey the Swag Bear", 
        "Iron Man", 
        "Jeff Green", 
        "BOS", 
        "Rajon Rondo", 
        "C-Green Smash Machine", 
        "Chris Johnson", 
        "Chris Babb", 
        "Keith Bogans", 
        "B Bass", 
        "The Predator", 
        "The C's", 
        "aabradley11", 
        "The Green", 
        "Boston Celtics", 
        "kellyolynyk", 
        "rajonrondo", 
        "faverani13", 
        "krishumphries", 
        "Sully", 
        "Crash", 
        "Green Monster", 
        "Sunshine", 
        "jared_sully0", 
        "TD Garden", 
        "Rajzilla", 
        "Celtics", 
        "The Garden", 
        "jerrydbayless", 
        "unclejeffgreen", 
        "Vitor Faverani", 
        "Boston Garden", 
        "Swag Bear", 
        "Olynyk", 
        "Doc", 
        "The Hump", 
        "Phil Pressey", 
        "Bayless", 
        "No-Pass Bass", 
        "Gerald Wallace", 
        "bestbetbass", 
        "celtics", 
        "Jared Sullinger", 
        "Fedex", 
        "Uncle Jeff", 
        "Joel Anthony", 
        "Avery Bradley", 
        "The Animal", 
        "Kris Humphries", 
        "Voltron", 
        "Celts", 
        "Swag", 
        "Pit Bull", 
        "Brandon Bass", 
        "Kelly Olynyk", 
        "philpressey", 
        "Jerryd", 
        "G-Force", 
        "Jerryd Bayless"
    ], 
    "Brooklyn": [
        "Blatche", 
        "JJ", 
        "The Kid", 
        "Mason Plumlee", 
        "ASqared06", 
        "Shaun Livingston", 
        "Slick", 
        "?????????", 
        "Go-Go Gadget Arms", 
        "ShaunLivingston", 
        "Teletovic33", 
        "TheJoeJohnson7", 
        "Kingpin", 
        "Brook Lopez", 
        "Cabbage Blatche", 
        "KG", 
        "D-Nasty", 
        "Plums", 
        "officialmt23", 
        "Jason Collins", 
        "KirilenkoNews", 
        "Dray Live", 
        "MT3", 
        "BKN", 
        "Armadillo Cowboy", 
        "Bulletproof", 
        "Brooklyn", 
        "D-Will", 
        "S Dot", 
        "drayblatche", 
        "Ziploc", 
        "Joe Cool", 
        "Mirza Teletovic", 
        "Pierce", 
        "Kirilenko", 
        "P-Sqaured", 
        "marquisteague25", 
        "Plumlee", 
        "Double", 
        "Kevin Garnett", 
        "Barclays Center", 
        "BrooklynNets", 
        "deronwilliams", 
        "Andray Blatche", 
        "Livingston", 
        "Marcus Thornton", 
        "T-Teeth", 
        "Marquis Teague", 
        "MirzaTeletovic", 
        "Alan Anderson", 
        "paulpierce34", 
        "RealBrookLopez", 
        "Joe Johnson", 
        "The Truth", 
        "Andrei Kirilenko", 
        "Paul Pierce", 
        "RealKGarnett", 
        "masonplumlee", 
        "Brooklyn Nets", 
        "Garnett", 
        "Teletovic", 
        "AK47", 
        "The Big Ticket", 
        "Nets", 
        "Deron Williams", 
        "Jorge Gutierrez"
    ], 
    "Charlotte": [
        "bismackbiyombo0", 
        "Al Jefferson", 
        "Josh McRoberts", 
        "Justin Hamilton", 
        "Cats", 
        "The Mop", 
        "Gary Neal", 
        "codyzeller", 
        "Luke Ridnour", 
        "Jannero Pargo", 
        "Bismack Biyombo", 
        "Kemba Walker", 
        "Frodo", 
        "The Cable Box", 
        "lukeridnour", 
        "Gerald Henderson", 
        "Big Al", 
        "Cool Hand Luke", 
        "CHA", 
        "ghjr09", 
        "kembawalker", 
        "Bobcats", 
        "Anthony Tolliver", 
        "Cody Zeller", 
        "Charlotte Bobcats", 
        "MKG14", 
        "Michael Kidd-Gilchrist", 
        "The Dread Pirate", 
        "Jeff Taylor", 
        "Brendan Haywood", 
        "Time Warner Cable Arena", 
        "Baby Huey", 
        "Lucky Luke", 
        "Chris Douglas-Roberts", 
        "jpargo1", 
        "the Big Classic", 
        "atolliver44"
    ], 
    "Chicago": [
        "mr_2eight1", 
        "Chicago Bulls", 
        "jimmerfredette", 
        "Joakim Noah", 
        "Jimmy Buckets", 
        "Tornike Shengelia", 
        "Jimmy G. Buckets", 
        "Tornike", 
        "MisterCBooz", 
        "Carlos Boozer", 
        "joakimnoah", 
        "drose", 
        "ChicagoBulls", 
        "Dr. No", 
        "Erik Murphy", 
        "Bulls", 
        "The Noble One", 
        "Mike Dunleavy", 
        "Jimmer Fredette", 
        "e_murphy31", 
        "The UC", 
        "Pooh", 
        "DJ Augustin", 
        "The Madhouse on Madison", 
        "nazrmohammed", 
        "D.J. Augustin", 
        "United Center", 
        "Jimmy Butler", 
        "Nazr Mohammed", 
        "CHI", 
        "Taj Gibson", 
        "Captain Kirk", 
        "tajgibson22", 
        "Kirk Hinrich", 
        "Derrick Rose", 
        "TokoShengelia23", 
        "Booze", 
        "D-Rose", 
        "TonySnell20", 
        "The Prophet", 
        "Shengelia", 
        "Tony Snell", 
        "Tokomotiv"
    ], 
    "Cleveland": [
        "masfresco", 
        "Shane Edwards", 
        "Spencer Hawes", 
        "Matthew Dellavedova", 
        "kyrieirving", 
        "Hee", 
        "Tristan Thompson", 
        "Quicken Loans Arena", 
        "Tyler Zeller", 
        "spencerhawes00", 
        "luoldeng9", 
        "Uncle Drew", 
        "Cavaliers", 
        "dionwaiters3", 
        "Sideshow Bob", 
        "Sideshow", 
        "jarrettjack03", 
        "Alonzo Gee", 
        "cavs", 
        "geealonzo", 
        "CLE", 
        "C_Felix0", 
        "realtristan13", 
        "The Q", 
        "Kyrie Irving", 
        "Luol Deng", 
        "matthewdelly", 
        "Wild Thing", 
        "Carrick Felix", 
        "Jarrett Jack", 
        "anthonybennett", 
        "Cleveland Cavaliers", 
        "Anderson Varejao", 
        "The Man from Sudan", 
        "zellertyler", 
        "Anthony Bennett", 
        "CJ Miles", 
        "Dion Waiters"
    ], 
    "Dallas": [
        "REALRICKLEDO1", 
        "WayneElli22", 
        "Wayne Ellington", 
        "Jose Calderon", 
        "AAC", 
        "Devin Harris", 
        "GalMekel33", 
        "Mekel", 
        "bwright34", 
        "D-Bert", 
        "Irk", 
        "The Human Exclamation Point", 
        "Half-Amazing", 
        "josemcalderon8", 
        "SamDalembert", 
        "Ellis", 
        "Crowder", 
        "The German Wunderkind", 
        "CJC9BOSS", 
        "Dalembert", 
        "Larkin", 
        "Ocho Special", 
        "The Haitian Sensation", 
        "The Germanator", 
        "swish41", 
        "DeJuan Blair", 
        "DAL", 
        "Batman", 
        "matrix31", 
        "DeJuan45", 
        "Ellington", 
        "Ricardo Ledo", 
        "Ricky Ledo", 
        "Diggler", 
        "Dallas Mavericks", 
        "Sarge", 
        "DallasMavs", 
        "Shawn Marion", 
        "Milkface", 
        "Nowitzki", 
        "The Cheese Factor", 
        "#Mavs", 
        "Mavericks", 
        "IamMonta", 
        "ShaneLarkin_3", 
        "The Ocho", 
        "Half-Man", 
        "DeJuan", 
        "Jae Crowder", 
        "Dev34Harris", 
        "Bernard James", 
        "VC", 
        "Half-A-Season", 
        "Vinsanity", 
        "The Mississippi Bullet", 
        "Air Canada", 
        "Samuel Dalembert", 
        "Carter", 
        "Shane Larkin", 
        "BernardRJames", 
        "Ledo", 
        "Dunking Deutschman", 
        "Vince Carter", 
        "The Matrix", 
        "American Airlines Center", 
        "Brandan Wright", 
        "Monta Ellis", 
        "Dirk Nowitzki", 
        "Gal Mekel", 
        "Marion", 
        "Dirk Digger", 
        "Calderon", 
        "iBall_", 
        "mrvincecarter15", 
        "Big Bucks"
    ], 
    "Denver": [
        "Anthony Randolph", 
        "DEN", 
        "TheARandolph", 
        "DarrellArthur00", 
        "KryptoNate", 
        "nate_robinson", 
        "JJ Hickson", 
        "janvesely24", 
        "Pepsi Center", 
        "Thirty2zero", 
        "Timofey", 
        "Timofey Mozgov", 
        "randyfoye", 
        "Chandler", 
        "Gallo", 
        "Kenneth Faried", 
        "The Can", 
        "Ty Lawson", 
        "JaVale", 
        "TimofeyMozgov", 
        "Quincy Miller", 
        "Nuggets", 
        "thirty2zero", 
        "JaVale McGee", 
        "Nate Robinson", 
        "Aaron Brooks", 
        "AB", 
        "Manimal", 
        "Evan Fournier", 
        "Danilo Gallinari", 
        "KennethFaried35", 
        "JaValeMcGee34", 
        "denvernuggets", 
        "Hickson", 
        "wilsonchandler", 
        "Darrell Arthur", 
        "qmillertime", 
        "Hickson21", 
        "Jan Vesely", 
        "Nate The Great", 
        "JJHickson31", 
        "gallinari8888", 
        "Timo_Mozgov", 
        "Fournier", 
        "Randy Foye", 
        "Mozgov", 
        "Faried", 
        "tylawson3", 
        "EvanFourmizz", 
        "Randolph", 
        "Wilson Chandler", 
        "Denver Nuggets"
    ], 
    "Detroit": [
        "Mr. Big Shot", 
        "Luigi Datome", 
        "Caldwell", 
        "BigJorts55", 
        "Peyton Siva", 
        "DET", 
        "RodneyStuckeyP3", 
        "jonasjerebko", 
        "Will Bynum", 
        "PeypeySiva3", 
        "BrandonJennings", 
        "Skillanueva", 
        "jsmooveNBA", 
        "Greg Monroe", 
        "Detroit Pistons", 
        "the_real_smooth", 
        "Billups", 
        "Rodney Stuckey", 
        "74Thrill", 
        "RS3", 
        "Kentavious", 
        "Jerebko", 
        "Kentavious Caldwell-Pope", 
        "Big Smooth", 
        "Singler", 
        "kylesingler", 
        "Jennings", 
        "Palace of Auburn Hills", 
        "Drummond", 
        "Tony Mitchell", 
        "Villanueva", 
        "C-Elite", 
        "Charlie Villanueva", 
        "Stuckey", 
        "TonyMitchUNENO", 
        "Kyle Singler", 
        "Chauncey Billups", 
        "Andre Drummond", 
        "Bynum", 
        "M10OSE", 
        "AndreDrummondd", 
        "Datome", 
        "Harrellson", 
        "Josh Harrellson", 
        "caldwellpope1", 
        "CV", 
        "J-Smoove", 
        "The Palace", 
        "Pistons", 
        "Josh Smith", 
        "CV3", 
        "GigiDatome", 
        "Gigi Datome", 
        "Hot Rod", 
        "Jonas Jerebko", 
        "Chauncey", 
        "cv31", 
        "Brandon Jennings", 
        "The Pterodactyl", 
        "Chief Lightning First Step"
    ], 
    "Golden State": [
        "Nemanja", 
        "Klay Thompson", 
        "Iggy", 
        "GSW", 
        "Warriors", 
        "dlee042", 
        "Oakland Coliseum Arena", 
        "andre", 
        "Bogut", 
        "Da White Howard", 
        "The Bogey Man", 
        "Ognjen Kuzmic", 
        "Crawford", 
        "Draymond Green", 
        "HBarnes", 
        "andrewbogut", 
        "Golden State Warriors", 
        "KlayThompson", 
        "Mospeights16", 
        "warriors", 
        "Festus Ezeli", 
        "Andre Iguodala", 
        "Klay", 
        "Festus", 
        "nedovic1624", 
        "Dolla Billz", 
        "Harrison Barnes", 
        "jermaineoneal", 
        "Marreese Speights", 
        "Jordan Crawford", 
        "ORACLE Arena", 
        "Jermaine O'Neal", 
        "Nedovic", 
        "The O", 
        "Andrew Bogut", 
        "The New Arena", 
        "stephencurry30", 
        "AI 2.0", 
        "Roaracle", 
        "Stephen Curry", 
        "Steve Blake", 
        "jcraw55", 
        "Money23Green", 
        "#Warriors", 
        "Jermaine ONeal", 
        "Speights", 
        "steveblake5", 
        "Nemanja Nedovic", 
        "Iguodala", 
        "Bogues", 
        "Los", 
        "fezzyfel", 
        "Bogey", 
        "TeamKlay", 
        "Draymond", 
        "David Lee"
    ], 
    "Houston": [
        "Terrence Alexander Jones", 
        "Asik", 
        "D12", 
        "Howard", 
        "Dwight Howard", 
        "Gregory Smith", 
        "dwighthoward", 
        "Thundercat", 
        "Houston Rockets", 
        "Lin-credible", 
        "Latin Assassin", 
        "Holla_At_Rob33", 
        "Francisco Garcia", 
        "Motiejunas", 
        "Chandler", 
        "James Harden", 
        "Robert Covington", 
        "Isaiah Canaan", 
        "Omri Casspi", 
        "Chandler Parsons", 
        "Frank", 
        "#Rockets", 
        "jlin7", 
        "Jeremy Lin", 
        "Casspi18", 
        "Super-Lintendo", 
        "Foul on You", 
        "Troy Daniels", 
        "Thunder", 
        "TerrenceJones1", 
        "Donatas Motiejunas", 
        "Lin-tastic", 
        "DonatasMot", 
        "DH12", 
        "Tip Dunk Eddy", 
        "Jordan Hamilton", 
        "SiP03", 
        "D-Bo", 
        "j_goin_ham", 
        "Parsons", 
        "OmerAsik", 
        "Harden", 
        "Beverley", 
        "ChandlerParsons", 
        "HOU", 
        "Rockets", 
        "Toyota Center", 
        "Omer", 
        "Dwight", 
        "D-Mo", 
        "Lin Dynasty", 
        "Omri", 
        "patbev21", 
        "Man Child", 
        "HoustonRockets", 
        "Canaan", 
        "Terrence Jones", 
        "Patrick Beverley", 
        "Lin-sanity", 
        "JHarden13", 
        "Ju_Smith4", 
        "Greg Smith", 
        "Superman", 
        "Casspi", 
        "Omer Asik", 
        "Donatas"
    ], 
    "Indiana": [
        "Copeland", 
        "David West", 
        "Hibbert", 
        "quietstorm_32", 
        "Donald Sloan", 
        "Bankers Life Fieldhouse", 
        "Roy Hibbert", 
        "Bynumite", 
        "Paul George", 
        "DX", 
        "The Fieldhouse", 
        "Rasual Butler", 
        "The X-Factor", 
        "stephensonlance", 
        "lscola4", 
        "Solomon Hill", 
        "kingxsolo", 
        "hoya2apacer", 
        "Paul George RR Martin", 
        "Luis Scola", 
        "Andrew Bynum", 
        "ianmahinmi", 
        "Lance Stephenson", 
        "dsloan15", 
        "CJ Watson", 
        "Paul_George24", 
        "George Hill", 
        "Rasual", 
        "Stephenson", 
        "Pacers", 
        "chefVOYardee", 
        "thekidet", 
        "Ian Mahinmi", 
        "king24george", 
        "Chris Copeland", 
        "Mahinmi", 
        "The A-Train", 
        "King George", 
        "Evan Turner", 
        "george_hill3", 
        "Socks", 
        "rasualbutler45", 
        "d_west30", 
        "Georgeous", 
        "IND", 
        "Sual Bop", 
        "D-West", 
        "Indiana Pacers", 
        "OptimusCope", 
        "Lavoy Allen"
    ], 
    "Los Angeles Clippers": [
        "Griffin", 
        "Staples Center", 
        "Jackson", 
        "Turkey Glue", 
        "Ryan Hollins", 
        "Barnes", 
        "Matt Barnes", 
        "Dudley", 
        "Matt_Barnes22", 
        "Darren Collison", 
        "Uno-Uno", 
        "Danny G", 
        "Los Angeles Clippers", 
        "Large Infant", 
        "Crawford", 
        "Willie Green", 
        "Bullock", 
        "LAClippers", 
        "Batman", 
        "Hollins", 
        "Chris Paul", 
        "dgranger33", 
        "Jordan", 
        "JJ Redick", 
        "TheRyanHollins", 
        "Hedo Turkoglu", 
        "Jamal Crawford", 
        "Junkyard Dog", 
        "DeAndre Jordan", 
        "WillieGreen33RO", 
        "deandrejordan", 
        "Reggie Bullock", 
        "JCrossover", 
        "JaredDudley619", 
        "LA Clippers", 
        "SJacksonNews", 
        "Turk", 
        "ReggieBullock35", 
        "Jared Dudley", 
        "Glu", 
        "Blake Griffin", 
        "Glen Davis", 
        "Redick", 
        "Stephen Jackson", 
        "#Clippers", 
        "Darren_Collison", 
        "JJRedick", 
        "LAC", 
        "blakegriffin32", 
        "Danny Granger", 
        "DeAndre", 
        "The Gift", 
        "Big Baby", 
        "CP3", 
        "iambigbaby11", 
        "Studley"
    ], 
    "Los Angeles Lakers": [
        "MarShon Brooks", 
        "Staples Center", 
        "Los Angeles Lakers", 
        "Jodie Meeks", 
        "Robert Sacre", 
        "KB-24", 
        "Gasol", 
        "jmeeks20", 
        "kobebryant", 
        "Marshon2", 
        "Black Mamba", 
        "paugasol", 
        "Kaman", 
        "The City", 
        "Farmar", 
        "Kent Bazemore", 
        "Pau Gasol", 
        "Nashty", 
        "JrFarmar", 
        "Crazy Clown", 
        "jordanchill43", 
        "MarShonbrooks", 
        "Kobe Bryant", 
        "Chris Kaman", 
        "Xavier Henry", 
        "SteveNash", 
        "MarShon", 
        "Meeks", 
        "Steve Nash", 
        "PG", 
        "J-Farm", 
        "Nick Young", 
        "Bryant", 
        "Hair Canada", 
        "Bobby_Sacre", 
        "Swaggy P", 
        "Shaggy", 
        "XavierHenry", 
        "Ryan Kelly", 
        "Bazemore", 
        "Lakers", 
        "Kendall Marshall", 
        "Wesley Johnson", 
        "Kob-Me", 
        "KButter5", 
        "Picasso", 
        "Jordan Hill", 
        "kentbazmore20", 
        "LAL", 
        "ChrisKaman", 
        "Sacre", 
        "Vino", 
        "The Caveman", 
        "RyanKelly34", 
        "lakers", 
        "Captain Canada", 
        "Bean Burrito", 
        "WesJohnson4", 
        "Spanish Fly", 
        "Kobe", 
        "Jordan Farmar", 
        "The Zombie", 
        "Lord of the Rings", 
        "NickSwagyPYoung", 
        "The Meal Ticket"
    ], 
    "Memphis": [
        "mconley11", 
        "aa000G9", 
        "Mike Miller", 
        "Memphis Grizzlies", 
        "Calathes", 
        "nick_calathes15", 
        "Prince of The Palace", 
        "James Johnson", 
        "Tony Allen", 
        "JJ", 
        "Conley", 
        "Nick Calathes", 
        "Ed Davis", 
        "Jon Leuer", 
        "Beno Udrih", 
        "eddavis32", 
        "FedExForum", 
        "Quincy Pondexter", 
        "Marc Gasol", 
        "Udrih", 
        "MikeMiller_13", 
        "Tanketa", 
        "kostakoufos", 
        "The Grindhouse", 
        "Pondexter", 
        "Spiderman", 
        "quincypondexter", 
        "\"Mike Conley", 
        "tay_prince", 
        "memgrizz", 
        "Tayshaun Prince", 
        "MacBo50", 
        "Courtney Lee", 
        "Kosta", 
        "Leuer", 
        "Kosta Koufos", 
        "MEM", 
        "Z-Bo", 
        "Grizzlies", 
        "Tay", 
        "MarcGasol", 
        "Koufos", 
        "Money Mike", 
        "courtneylee2211", 
        "JLeu30", 
        "Zach Randolph", 
        "jr.\"", 
        "Randolph", 
        "BenoUdrih1"
    ], 
    "Miami": [
        "OfficialRashard", 
        "AAA", 
        "MIA", 
        "Udonis", 
        "Flash", 
        "Dwyane Wade", 
        "Justin Hamilton", 
        "Sugar", 
        "G.O.", 
        "dwyanewade", 
        "LeBron James", 
        "jonesforthree", 
        "CB4", 
        "thisisud", 
        "Beasley", 
        "Justin_41", 
        "Miami Heat", 
        "Greg Oden", 
        "Sugar Ray", 
        "Beastley", 
        "King James", 
        "easyst0", 
        "Sweet Lew", 
        "Chris Andersen", 
        "Jesus Shuttlesworth", 
        "Udonis Haslem", 
        "Michael Beasley", 
        "Haslem", 
        "chrisbosh", 
        "Heat", 
        "Chris Bosh", 
        "MiamiHeat", 
        "Chalmers", 
        "11ChrisAndersen", 
        "Pookie", 
        "PG30_MIA", 
        "The Chosen One", 
        "L-Train", 
        "Battier", 
        "Rashard Lewis", 
        "Super Mario", 
        "The Triple A", 
        "Young Fella", 
        "CB", 
        "kingjames", 
        "Mario Chalmers", 
        "Rashard", 
        "Birdman", 
        "Daddyluv2250", 
        "B-Easy", 
        "The King", 
        "TDouglas_23", 
        "Bron Bron", 
        "Toney Douglas", 
        "D-Wade", 
        "LeBron", 
        "American Airlines Arena", 
        "The Boshtrich", 
        "Jesus", 
        "rayallentwenty", 
        "Super Nintendo", 
        "LBJ", 
        "Superintendent", 
        "J. Shuttlesworth", 
        "Shane Battier", 
        "Ray Allen", 
        "D. Wade", 
        "shanebattier", 
        "Alien Nation", 
        "mchalmers15", 
        "Cole Train", 
        "Rio", 
        "James Jones", 
        "Norris Cole", 
        "The Akron Hammer", 
        "Boshasaurus", 
        "Battle", 
        "UD", 
        "greenRAYn20", 
        "Ray Ray", 
        "Easy Mo Be"
    ], 
    "Milwaukee": [
        "Raduljica", 
        "Nate Wolters", 
        "erSova7", 
        "MIL", 
        "BrandonKnight07", 
        "MRaduljica9", 
        "larrysanders", 
        "Ilyasova", 
        "Giannis", 
        "Carlos Delfino", 
        "ErsanIlyasova7", 
        "Wolters", 
        "Khris Middleton", 
        "ekpeudoh", 
        "Ekpe Udoh", 
        "Pachulia", 
        "Miroslav", 
        "ojmayogrizz", 
        "Ersan Ilyasova", 
        "O.J. Mayo", 
        "NateWolters", 
        "Knight", 
        "_john_henson_", 
        "OJ Mayo", 
        "Larry Sanders", 
        "Milwaukee Bucks", 
        "The B.C.", 
        "John Henson", 
        "Brandon Knight", 
        "SessionsRamon", 
        "Ramon Sessions", 
        "Jeff Adrien", 
        "Miroslav Raduljica", 
        "Udoh", 
        "cabezadelfino", 
        "Giannis Antetokounmpo", 
        "Turkish Thunder", 
        "G_ante34", 
        "Adrien4", 
        "Chris Wright", 
        "Khris22m", 
        "zaza27", 
        "Antetokounmpo", 
        "Zaza Pachulia", 
        "Ekpe", 
        "Bucks", 
        "BMO Harris Bradley Center"
    ], 
    "Minnesota": [
        "Shved23", 
        "GSWTuriaf", 
        "C-Brew", 
        "Budinger", 
        "Target Center", 
        "Timberwolves", 
        "MNTimberwolves", 
        "Mbahamoute", 
        "Robbie Hummel", 
        "Dante Cunningham", 
        "Ronny Turiaf", 
        "The Drunken Dribbler", 
        "Gorgui Dieng", 
        "Pekovic", 
        "K-Money", 
        "C-B", 
        "kevinlove", 
        "Kevin Love", 
        "NikolaPekovic14", 
        "Kid N Play", 
        "RobbieHummel", 
        "Moute", 
        "Chase Budinger", 
        "realAJPrice", 
        "Alexey Shved", 
        "JJ Barea", 
        "Shabazz Muhammad", 
        "Nikola Pekovic", 
        "K-Mart", 
        "DlamarC33", 
        "Corey Brewer", 
        "rickyrubio9", 
        "CBudinger", 
        "Ricky Rubio", 
        "Kevin Martin", 
        "CoreyBrewer13", 
        "GorguiDieng", 
        "K-Love", 
        "Shved", 
        "Minnesota Timberwolves", 
        "phenom15balla", 
        "Turiaf", 
        "jjbareapr", 
        "A.J. Price", 
        "AJ Price", 
        "Gorgui", 
        "Rubio", 
        "Dieng", 
        "Luc Mbah a Moute", 
        "#Twolves"
    ], 
    "New Orleans": [
        "jrue_holiday11", 
        "theofficialeg10", 
        "Luke Babbitt", 
        "AjincaAlexis42", 
        "MrAnthonyMorrow", 
        "The Hobbit", 
        "Darius Miller", 
        "Jeff Withey", 
        "PelicansNBA", 
        "tyrekeevans", 
        "JeffWithey", 
        "farouq1", 
        "Smoothie King Center", 
        "Ryan Anderson", 
        "gregstiemsma", 
        "LukeBabbitt", 
        "Tyreke Evans", 
        "Jason Smith", 
        "Anthony Morrow", 
        "Pelicans", 
        "Austin Rivers", 
        "ryananderson33", 
        "Eric Gordon", 
        "Jrue Holiday", 
        "Anthony Davis", 
        "JasonSmith014", 
        "Greg Stiemsma", 
        "Al-Farouq Aminu", 
        "Alexis Ajinca", 
        "New Orleans Pelicans", 
        "Chocolate Reign", 
        "austinrivers25", 
        "AntDavis23", 
        "NOP", 
        "Brian Roberts"
    ], 
    "New York": [
        "TheRealJRSmith", 
        "Tim Hardaway Jr", 
        "Cole Aldrich", 
        "Pablo Prigioni", 
        "toure_murry", 
        "Felton", 
        "Madison Square Garden", 
        "NYK", 
        "Swish", 
        "carmeloanthony", 
        "Melo", 
        "MSG", 
        "Kenyon Martin", 
        "nyknicks", 
        "The Magician", 
        "Chandler", 
        "The World's Most Famous Arena", 
        "Shumpert", 
        "The Mecca", 
        "Toure Murry", 
        "Raymond Felton", 
        "Earl Clark", 
        "ShanWow", 
        "New York Knicks", 
        "Iman Shumpert", 
        "Amareisreal", 
        "The Garden", 
        "Felts", 
        "JR Smith", 
        "Kenyon", 
        "Stoudemire", 
        "Shannon Brown", 
        "#Knicks", 
        "Andrea Bargnani", 
        "PPrigioni9", 
        "Sir Dunks-A-Lot", 
        "J.R. Smith", 
        "Amar'e Stoudemire", 
        "Tyson Chandler", 
        "Carmelo Anthony", 
        "Prigioni", 
        "ShannonBrown", 
        "Hardaway", 
        "I_Am_Iman", 
        "Il Mago", 
        "Carmelo", 
        "Bad Ass Yellow Boy", 
        "tysonchandler", 
        "RFeltonGBMS", 
        "Aldrich", 
        "colea45", 
        "Jeremy Tyler", 
        "KenyonMartinSr", 
        "jeremytyler3", 
        "T_HardJR", 
        "Bargnani", 
        "AndreaBargnani"
    ], 
    "Oklahoma City": [
        "Derek Fisher", 
        "Caron Butler", 
        "Caronimo", 
        "Swamp Thang", 
        "Reggie Williams", 
        "nickcollison4", 
        "Perk", 
        "Thunder", 
        "Westbrook", 
        "The Big Dongo from the Kongo", 
        "FlyDre21", 
        "sergeibaka9", 
        "CB3", 
        "Hasheem", 
        "HasheemTheDream", 
        "K-Dog", 
        "Cat", 
        "Hasheem Thabeet", 
        "Ibaka", 
        "Kevin Durant", 
        "okcthunder", 
        "Collison", 
        "russwest44", 
        "Perry_Jones1", 
        "realstevenadams", 
        "Tough Juice", 
        "Thabo", 
        "Reggie", 
        "Border Collie", 
        "Serge Protector", 
        "Steven Adams", 
        "Loud City", 
        "Durant", 
        "ThaboSefolosha", 
        "Reggie Jackson", 
        "Serge Ibaka", 
        "D-Fish", 
        "Kendrick Perkins", 
        "Perry Jones", 
        "Thabeet", 
        "Thabo Sefolosha", 
        "K-Smoove", 
        "Chesapeake Energy Arena", 
        "Kendrick", 
        "realtuffjuice", 
        "Slim Reaper", 
        "OklahomaCityThunder", 
        "Jeremy Lamb", 
        "jlamb", 
        "kendrickperkins", 
        "rjOKCson_15", 
        "derekfisher", 
        "KD", 
        "The Durantula", 
        "Fish", 
        "Fashion Icon", 
        "reggiew55", 
        "Russell Westbrook", 
        "Andre Roberson", 
        "The Second Coming", 
        "OKC", 
        "I-block-a", 
        "Nick Collison", 
        "The Thunderdome", 
        "Oklahoma City", 
        "The Peake", 
        "Sefolosha", 
        "kdtrey5"
    ], 
    "Orlando": [
        "Adonis Thomas", 
        "jasonmaxiell", 
        "arronafflalo", 
        "Spell Check", 
        "DLamb20", 
        "ETwaun Moore", 
        "Amway Center", 
        "dedmon_21", 
        "jameernelson", 
        "Orlando Magic", 
        "Jameer Nelson", 
        "Ronnie Price", 
        "Dewayne Dedmon", 
        "Andrew Nicholson", 
        "Kyle OQuinn", 
        "tobias31", 
        "Nikola Vucevic", 
        "Mad Max", 
        "Tobias Harris", 
        "Magic", 
        "moe_harkless", 
        "vicoladipo", 
        "Lightning", 
        "Arron Afflalo", 
        "Jason Maxiell", 
        "Orlando_Magic", 
        "O-Rena", 
        "J-Max", 
        "nicholaf44", 
        "Crib Midget", 
        "ORL", 
        "Maurice Harkless", 
        "Mighty Mouse", 
        "Victor Oladipo", 
        "etwaun55", 
        "Doron Lamb"
    ], 
    "Philadelphia": [
        "EYMaynor3", 
        "Lorenzo Brown", 
        "MCW1", 
        "JA_Five", 
        "Henry Sims", 
        "Philadelphia 76ers", 
        "yungsmoove21", 
        "Elliot Williams", 
        "byron22mullens", 
        "Philadelphia Sixers", 
        "htdahot_twitta", 
        "J-Rich", 
        "amoultrie", 
        "Thaddeus Young", 
        "Brandon Davies", 
        "0BrandonDavies", 
        "NerlensNoel3", 
        "Wells Fargo Center", 
        "Mullens", 
        "Byron Mullens", 
        "76ers", 
        "James Anderson", 
        "Hollis Thompson", 
        "Nerlens Noel", 
        "thekidet", 
        "Jarvis Varnado", 
        "TWroten_LOE", 
        "Mr_5Hundred", 
        "Arnett Moultrie", 
        "Tony Wroten", 
        "PHI", 
        "ewill901", 
        "Evan Turner", 
        "ZoBrown7", 
        "Jason Richardson", 
        "jrich23", 
        "H_Sims14", 
        "Michael Carter-Williams", 
        "Eric Maynor", 
        "Sixers", 
        "Philly", 
        "Lavoy Allen"
    ], 
    "Phoenix": [
        "bigmek50", 
        "Markieff Morris", 
        "keefmorris", 
        "Channing Frye", 
        "Ice", 
        "milesplumlee13", 
        "TheBlur_Barbosa", 
        "Blackula", 
        "the Blur", 
        "The Brazilian Bomber", 
        "Emeka Okafor", 
        "Dchristmas22", 
        "Dionte", 
        "Temple", 
        "Goran Dragic", 
        "High-5", 
        "Barbosa", 
        "EO-50", 
        "LB", 
        "alexlen", 
        "Plumlee", 
        "Ish Smith", 
        "ishsmith", 
        "G-Money", 
        "Goran", 
        "TheBlurBarbosa", 
        "Gerald Green", 
        "PJ Tucker", 
        "Buffet of Goodness", 
        "Leandrinho", 
        "Mini Lebron", 
        "MookMorris2", 
        "Oak Tree", 
        "Goran_Dragic", 
        "Dragic", 
        "Alex Len", 
        "Eric Bledsoe", 
        "Leandro Barbosa", 
        "EBled2", 
        "Phoenix Suns", 
        "Brazilian Blur", 
        "Archie Goodwin", 
        "Marcus Morris", 
        "Dionte Christmas", 
        "Markieff", 
        "US Airways Center", 
        "A1Laflare10", 
        "Channing", 
        "Miles Plumlee", 
        "Shavlik Randolph", 
        "Suns", 
        "Frye", 
        "PJTUCKER17", 
        "Bledsoe", 
        "The Snake Pit", 
        "PHX", 
        "The Purple Palace", 
        "GgreenJr25", 
        "Channing_Frye"
    ], 
    "Portland": [
        "mowilliams", 
        "McCollum", 
        "Batum", 
        "Earl Watson", 
        "Joel Freeland", 
        "LaMarcus Aldridge", 
        "JF", 
        "joelfreeland", 
        "nicolas88batum", 
        "Dorell Wright", 
        "Crabbe", 
        "Portland Trail Blazers", 
        "DWRIGHTWAY1", 
        "Earl_Watson", 
        "eegabeeva88", 
        "Robin Lopez", 
        "POR", 
        "trobinson0", 
        "CJ McCollum", 
        "Wesley Matthews", 
        "Victor_Claver", 
        "Blazers", 
        "Victor Claver", 
        "Trail Blazers", 
        "Mo Williams", 
        "pdxtrailblazers", 
        "LaMarcus", 
        "Moda Center", 
        "Lillard", 
        "Damian Lillard", 
        "Nicolas Batum", 
        "Meyers Leonard", 
        "CJMcCollum", 
        "L-Train", 
        "Dame_Lillard", 
        "4531?54?N12240?0?W", 
        "Allencrabbe", 
        "LMA", 
        "Dorell", 
        "The Hitman", 
        "Will Barton", 
        "Claver", 
        "aldridge_12", 
        "Thomas Robinson", 
        "Aldridge", 
        "WillTheThrillB5", 
        "Allen Crabbe", 
        "MeyersLeonard11", 
        "wessywes2"
    ], 
    "Sacramento": [
        "RayMac3", 
        "Royce White", 
        "BenMcLemore", 
        "JT", 
        "The Joker", 
        "CarlLandry", 
        "Pace_O11", 
        "Aaron Gray", 
        "highway_30", 
        "Derrick Williams", 
        "RealDwill7", 
        "SAC", 
        "boogiecousins", 
        "SippiCountryBoi", 
        "sacramentokings", 
        "Sacramento Kings", 
        "Ray McCallum", 
        "The Jet", 
        "QuincyAcy", 
        "JET", 
        "Travis Outlaw", 
        "Sleep Train Arena", 
        "Isaiah Thomas", 
        "Quincy Acy", 
        "reggieevans30", 
        "Reggie Evans", 
        "jasonterry31", 
        "Rudy Gay", 
        "Orlando Johnson", 
        "Jason Terry", 
        "Carl Landry", 
        "Isaiah_Thomas2", 
        "rudygay22", 
        "Ben McLemore", 
        "DeMarcus Cousins", 
        "jtthekid", 
        "The Collector", 
        "Kings", 
        "AaronGray_34", 
        "Jason Thompson"
    ], 
    "San Antonio": [
        "Tim Duncan", 
        "Groundhog Day", 
        "San Antonio Spurs", 
        "Patty Mills", 
        "The Big Fundamental", 
        "Mr. Longoria", 
        "Jeff Ayres", 
        "marcobelinelli", 
        "The Red Rocket", 
        "3D", 
        "Gino", 
        "Austin Daye", 
        "Marco Belinelli", 
        "adaye5", 
        "TP", 
        "Balki Bartokomous", 
        "tonyparker", 
        "Parisian Torpedo", 
        "Death & Taxes", 
        "SAS", 
        "aronbaynes", 
        "El Contusione", 
        "San Antonio", 
        "Aron Baynes", 
        "Obi-Wan Ginobili", 
        "Manu Ginobili", 
        "Frenchie", 
        "Timmy D", 
        "The Main Butter & Egg Man", 
        "Matt Bonner", 
        "theborisdiaw", 
        "TD", 
        "Spurs", 
        "Tiago Splitter", 
        "Danny Green", 
        "Beli", 
        "dgreen_14", 
        "Cory_Joe", 
        "tiagosplitter", 
        "Cory Joseph", 
        "Timmay", 
        "spurs", 
        "Tony Parker", 
        "AT&T Center", 
        "Boris Diaw", 
        "Slam Duncan", 
        "Fiery Francophile", 
        "Kawhi Leonard"
    ], 
    "Toronto": [
        "TOR", 
        "Toronto Raptors", 
        "The ACC", 
        "greivisvasquez", 
        "Amir Johnson", 
        "landryfields", 
        "Julyan Stone", 
        "Dwight Buycks", 
        "BuycksWorld13", 
        "Nando De Colo", 
        "Kyle Lowry", 
        "klow7", 
        "thans50", 
        "Patrick Patterson", 
        "t_dotflight31", 
        "demar_derozan", 
        "Terrence Ross", 
        "Landry Fields", 
        "c_hayes44", 
        "Buck", 
        "The Hangar", 
        "Greivis Vasquez", 
        "Tyler Hansbrough", 
        "John Salmons", 
        "pdpatt", 
        "Jonas Valanciunas", 
        "Chuck Hayes", 
        "Air Canada Centre", 
        "stevenovak16", 
        "Raptors", 
        "JValanciunas", 
        "NandoDeColo", 
        "Centre Air Canada", 
        "DeMar DeRozan", 
        "Steve Novak", 
        "raptors", 
        "iamamirjohnson"
    ], 
    "Utah": [
        "AlecBurks10", 
        "Andris Biedrins", 
        "John Lucas III", 
        "rudygobert15", 
        "Richard Jefferson", 
        "Jeremy Evans", 
        "EnergySolutions Arena", 
        "JeremyEvans40", 
        "Alec Burks", 
        "Malcolm Thomas", 
        "Gordon Hayward", 
        "Enes Kanter", 
        "Trey_Burke3", 
        "Jazz", 
        "utahjazz", 
        "gordonhayward", 
        "Enes_Kanter", 
        "Ian Clark", 
        "Luke1luk", 
        "Brandon Rush", 
        "UTA", 
        "Diante Garrett", 
        "BRush_25", 
        "kingarrett10", 
        "Derrick Favors", 
        "Beans", 
        "ESA", 
        "Dre", 
        "Malcolm4Thomas", 
        "Utah Jazz", 
        "Trey Burke", 
        "IanClark", 
        "Rudy Gobert", 
        "RJ", 
        "Marvin Williams", 
        "DFavors14"
    ], 
    "Washington": [
        "The Definition", 
        "Drew Gooden", 
        "The Phone Booth", 
        "Otto Porter", 
        "Wizards", 
        "Bradley Beal", 
        "Kevin Seraphin", 
        "The Big Drizzle", 
        "trevorariza", 
        "The Polish Hammer", 
        "Switchblade", 
        "John Wall", 
        "WAS", 
        "Garrett Temple", 
        "Andre Miller", 
        "35_Fitz", 
        "Washington Wizards", 
        "Martell Webster", 
        "cheddahcheese7", 
        "Chris Singleton", 
        "Al Harrington", 
        "glenrice41", 
        "WashWizards", 
        "Trevor Booker", 
        "Glen Rice", 
        "c_sing31", 
        "Cobra", 
        "GTemp14", 
        "kevin_seraphin", 
        "Baby Al", 
        "drewgooden", 
        "Verizon Center", 
        "The Truth", 
        "Trevor Ariza", 
        "john_wall", 
        "Nene", 
        "andremiller7", 
        "martellwebster", 
        "Marcin Gortat", 
        "mgortat", 
        "realdealbeal23"
    ]
}
