keywords = {
"Dreyer & Reinbold Kingdom Racing" : [ 
"Sage Karam",
"@sagekaram",
"IndyCar",
],
"Team Penske" : [ 
"Will Power",
"@12WillPower",
"AngryBird",
"Helio Castroneves",
"@h3lio",
"Spider-Man",
"Juan Pablo Montoya",
"@jpmontoya",
"Monty",
"Mont-ster",
],
"Target Chip Ganassi Racing" : [ 
"Scott Dixon",
"@scottdixon9",
"Tony Kanaan",
"@TonyKanaan",
"Boom Boom",
],
"KV AFS Racing" : [ 
"Sebastian Saavedra",
"@sebsaavedra",
],
"A.J. Foyt Enterprises" : [ 
"Takuma Sato",
"@takumasatoracer",
"Crashuma",
"Martin Plowman",
"@plowey",
"Plowey",
],
"KV Racing Technology" : [ 
"James Davison",
"@JDDavison007",
"Townsend Bell",
"@TownsendBell99",
],
"Lazier Partners Racing Inc." : [ 
"Buddy Lazier",
],
"NTT Data Chip Ganassi Racing" : [ 
"Ryan Briscoe",
"@Ryan_Briscoe",
"Brisco County Jr.",
],
"Schmidt Peterson Motorsports" : [ 
"Simon Pagenaud",
"@simonpagenaud",
"Jean Girard",
"Mikhail Aleshin",
"@MikhailAleshin",
"Jacques Villeneuve",
"@27villeneuve",
],
"Sarah Fisher Hartman Racing" : [ 
"Josef Newgarden",
"@josefnewgarden",
"Racer of Tomorrow",
"Alex Tagliani",
"@tagliani",
],
"BHA/BBM with Curb-Agajanian" : [ 
"Jack Hawksworth",
"@jackhawk91",
],
"Novo Nordisk Chip Ganassi Racing" : [ 
"Charlie Kimball",
"@racewithinsulin",
],
"KVSH Racing" : [ 
"Sebastien Bourdais",
"@BourdaisOnTrack",
"Seabass",
"Frenchy",
"Froggy",
"Kermit the frog",
],
"Dale Coyne Racing" : [ 
"Justin Wilson",
"@justin_wilson",
"",
"Carlos Huertas",
"@Carlos_Huertas",
"Pippa Mann",
"@PippaMann",
],
"Ed Carpenter Racing" : [ 
"Mike Conway",
"@Mikeconway26",
"Conweezey",
"Ed Carpenter",
"@edcarpenter20",
"Special ED",
"JR Hildebrand",
"@JRHildebrand",
],
"Andretti Autosport" : [ 
"Ryan Hunter-Reay",
"@RyanHunterReay",
"The Greatest Spectacle in Racing",
"Captain America",
"Marco Andretti",
"@marcoandretti",
"Driver of the Century",
"James Hinchcliffe",
"@hinchtown",
"Mayor of Hinchtown",
"Hinch",
"Kurt Busch",
"@KurtBusch",
"Franck Montagny",
],
"Andretti Autosport - HVM Racing" : [ 
"Carlos Munoz",
"@CarlosMunoz034",
],
"Rahal Letterman Lanigan Racing" : [ 
"Graham Rahal",
"@grahamrahal",
"The son of the stache",
"Oriol Servia",
"@OriolServia"
]
}
